import {useCallback,useEffect,useState} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {supabase} from './supabase';
import './BookingIntakes.css';
type Row={id:string;patient_name:string;email:string;visit_type:string;state:string;created_at:string;client_id:string|null;reservation_id:string|null;request_contact:string|null};
type Observation={id:string;symptom_code:string;label:string;dimension:string;value:number|null;unit:string;instrument:string;instrument_version:string;recall_days:number;respondent_role:string;body_region:string|null;laterality:string|null;recorded_at:string;state?:string};
const stateLabels:Record<string,string>={identity_pending:'Identidad por vincular',pending_review:'Por revisar',reviewed:'Revisado',published:'Publicado en portal'};
const dimensionLabels:Record<string,string>={severity_7d:'Intensidad',frequency_7d:'Días con molestias',interference_7d:'Interferencia'};
async function call(action:string,payload:Record<string,unknown>={}){const {data,error}=await supabase.rpc('healen_intake_staff',{action,payload});if(error)throw new Error(error.code==='42501'?'Este apartado requiere un perfil médico o administrador activo.':error.message);return data;}
function HumanValue({value,labels}:{value:any;labels:Record<string,string>}){if(value===null||value===undefined)return <span>Sin dato</span>;if(typeof value==='boolean')return <span>{value?'Sí':'No'}</span>;if(typeof value!=='object')return <span>{labels[String(value)]||String(value)}</span>;if(value.missing)return <span>{labels[value.missing]||'No informado / pendiente de conversar'}</span>;return <dl className="intake-values">{Object.entries(value).map(([key,v])=><div key={key}><dt>{Array.isArray(value)?Number(key)+1:labels[key]||key}</dt><dd><HumanValue value={v} labels={labels}/></dd></div>)}</dl>;}
function ProtocolQuestion({field:f,labels}:{field:any;labels:Record<string,string>}){const option=(v:any)=>typeof v==='boolean'?(v?'Sí':'No'):labels[String(v)]||String(v);return <div className="protocol-field"><strong>{f.label}</strong><p>{f.type==='private_upload'?'Adjunto opcional':'Respuesta obligatoria cuando aplique'}</p>{f.options&&<p>Opciones: {f.options.map(option).join(' / ')}</p>}{f.missingOptions&&<p>Alternativas explícitas: {f.missingOptions.map(option).join(' / ')}</p>}{f.min!==undefined&&<p>Escala: {f.min} a {f.max}{f.anchors?' · '+Object.entries(f.anchors).map(([k,v])=>k+': '+v).join(' · '):''}</p>}{(f.showIf||f.showIfAny)&&<p>Se muestra cuando: {Object.entries(f.showIf||f.showIfAny).map(([k,v])=>(labels[k]||k)+': '+(Array.isArray(v)?v.map(option).join(' / '):option(v))).join('; ')}</p>}{f.showIfPositive&&<p>Se muestra si {labels[f.showIfPositive]||f.showIfPositive} es mayor que cero.</p>}{f.repeatSource&&<p>Se repite para cada molestia prioritaria (máximo tres).</p>}{f.fields?.map((c:any)=><ProtocolQuestion key={c.id} field={c} labels={labels}/>)}{f.module&&<p>Detalles: {f.module}</p>}</div>;}
function Progress({points}:{points:Observation[]}){const reduced=useReducedMotion();const groups=Object.values(points.filter(p=>p.value!==null).reduce<Record<string,Observation[]>>((all,p)=>{const key=[p.symptom_code,p.dimension,p.unit,p.instrument,p.instrument_version,p.recall_days,p.respondent_role,p.body_region,p.laterality].join('|');(all[key]??=[]).push(p);return all;},{}));const [selected,setSelected]=useState(0);const rows=(groups[Math.min(selected,groups.length-1)]||[]).sort((a,b)=>a.recorded_at.localeCompare(b.recorded_at));if(!rows.length)return <p>No hay mediciones numéricas para graficar.</p>;const min=Date.parse(rows[0].recorded_at),max=Date.parse(rows[rows.length-1].recorded_at);const ymax=rows[0].unit==='days'?7:10;const coords=rows.map(p=>[rows.length===1?250:25+(Date.parse(p.recorded_at)-min)/Math.max(1,max-min)*450,155-Number(p.value)/ymax*130]);return <section className="intake-progress"><h3>Evolución reportada</h3><label>Medición<select value={Math.min(selected,groups.length-1)} onChange={e=>setSelected(Number(e.target.value))}>{groups.map((g,i)=><option key={i} value={i}>{g[0].label} · {dimensionLabels[g[0].dimension]} · {g[0].body_region||'Sin región'} · {g[0].respondent_role==='self'?'Paciente':'Representante'}</option>)}</select></label><p>Últimos {rows[0].recall_days} días por reporte · {rows[0].instrument} v{rows[0].instrument_version} · Autorreporte</p><svg viewBox="0 0 500 180" role="img" aria-label={rows.map(p=>`${new Date(p.recorded_at).toLocaleDateString('es-CO')}: ${p.value} ${p.unit}`).join('; ')}><line x1="25" x2="475" y1="155" y2="155" stroke="#dfd5e5"/><text x="5" y="158" fontSize="10">0</text><text x="5" y="28" fontSize="10">{ymax}</text>{rows.length>1&&<motion.path key={selected} d={coords.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ')} fill="none" stroke="#7a1f9b" strokeWidth="2" initial={{pathLength:reduced?1:0}} animate={{pathLength:1}} transition={{duration:reduced?0:.7}}/>}{coords.map(([x,y],i)=><circle key={rows[i].id} cx={x} cy={y} r="4" fill="#7a1f9b"><title>{new Date(rows[i].recorded_at).toLocaleString('es-CO')}: {rows[i].value}</title></circle>)}</svg><table><thead><tr><th>Fecha</th><th>Valor</th><th>Estado</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{new Date(p.recorded_at).toLocaleDateString('es-CO')}</td><td>{p.value} {p.unit}</td><td>{stateLabels[p.state||'pending_review']}</td></tr>)}</tbody></table></section>;}
export function BookingIntakes({clientId,patients=[]}:{clientId?:string;patients?:Array<{clientUuid?:string;name:string}>}){
 const [rows,setRows]=useState<Row[]>([]),[detail,setDetail]=useState<any>(null),[protocols,setProtocols]=useState<any[]>([]),[points,setPoints]=useState<Observation[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState(''),[verified,setVerified]=useState(false),[note,setNote]=useState(''),[showProtocols,setShowProtocols]=useState(false),[approved,setApproved]=useState<Record<string,boolean>>({});
 const load=useCallback(async()=>{try{const [list,ps]=await Promise.all([call('list',clientId?{clientId}:{}),call('protocols')]);setRows(list||[]);setProtocols(ps||[]);if(clientId)setPoints(await call('progress',{clientId}));setError('');}catch(e){setError((e as Error).message);}},[clientId]);useEffect(()=>{load();},[load]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const labels:Record<string,string>={self:'Paciente',representative:'Representante',yes:'Sí',no:'No',unknown:'No lo sé',discuss_at_visit:'Conversar en consulta',not_applicable:'No aplica',selected:'Opciones seleccionadas',priority:'Prioritarios',otherText:'Descripción de otra molestia',missing:'Sin dato',none:'Ninguno'};
 for(const p of protocols){Object.assign(labels,p.definition.optionLabels||{});for(const symptom of p.definition.symptomCatalog||[])labels[symptom.code]=symptom.label;}
 for(const p of protocols)for(const fs of Object.values(p.definition.modules) as any[])for(const f of fs)labels[f.id]=f.label;
 for(const p of protocols)for(const f of p.definition.sourceDefinition.fields||[])for(const c of f.properties?.choices||[])labels[c.id]=c.label;
 return <section className="booking-intakes"><header><div><span className="eyebrow">Agendamiento Healen</span><h2>{clientId?'Cuestionarios y evolución':'Recepción clínica de citas'}</h2></div><button className="btn" disabled={busy} onClick={load}>Actualizar</button></header>{error&&<p role="alert" className="intake-error">{error}</p>}{!clientId&&<button className="btn" onClick={()=>setShowProtocols(!showProtocols)}>Revisar protocolos antes de publicar</button>}{showProtocols&&protocols.map(p=><details key={p.visit_type+p.version}><summary>{p.visit_type==='initial'?'Ingreso':'Seguimiento'} · v{p.version} · {p.approved_at?'Aprobado':'Pendiente'}</summary><p>Revisión clínica de contenido, obligatoriedad y saltos. La aprobación habilita este protocolo cuando se abra la agenda.</p>{Object.entries(p.definition.modules).filter(([key])=>['booking_contact','identity',p.visit_type,'virtual','symptom_history','symptom_measurement','reported_product','digestive_context','sleep_context'].includes(key)).map(([key,fields])=><section key={key}><h4>{key}</h4>{(fields as any[]).map(f=><ProtocolQuestion key={f.id} field={f} labels={labels}/>)}</section>)}<details><summary>Fuente y trazabilidad de las 29 preguntas originales</summary>{(p.definition.sourceMapping.items||[]).map((f:any)=><div key={f.sourceId}><strong>{f.sourceQuestion}</strong><p>{f.targetFields.map((id:string)=>labels[id]||id).join(' · ')}</p><p>{f.reason}</p></div>)}</details>{!p.approved_at&&<><label><input type="checkbox" checked={!!approved[p.visit_type]} onChange={e=>setApproved({...approved,[p.visit_type]:e.target.checked})}/> Revisé el contenido clínico, opciones y saltos de esta versión.</label><button className="btn btn--primary" disabled={busy||!approved[p.visit_type]} onClick={()=>run(async()=>{await call('approve_protocol',{visitType:p.visit_type,version:p.version,hash:p.content_hash,reviewed:true});})}>Aprobar esta versión</button></>}</details>)}
 {rows.length===0&&!error&&<p>No hay cuestionarios {clientId?'vinculados a este paciente':'pendientes de revisión'}.</p>}<div className="intake-list">{rows.map(r=><button key={r.id} className={detail?.id===r.id?'selected':''} onClick={()=>run(async()=>{setDetail(await call('detail',{id:r.id}));setTarget('');setVerified(false);setNote('');})}><strong>{r.visit_type==='initial'?'Ingreso':'Seguimiento'} · {r.patient_name}</strong><span>{new Date(r.created_at).toLocaleString('es-CO')} · {stateLabels[r.state]}{r.request_contact==='true'?' · Solicitó contacto antes de la cita':''}</span></button>)}</div>
 {detail&&<article className="intake-detail"><header><h3>{detail.visit_type==='initial'?'Ingreso':'Seguimiento'} · {detail.answers.patient_name}</h3><button className="btn" onClick={()=>setDetail(null)}>Cerrar</button></header><p>{stateLabels[detail.state]} · Autorreporte recibido el {new Date(detail.created_at).toLocaleString('es-CO')} · Protocolo {detail.protocol_version}</p>{Object.entries(detail.answers).map(([key,value])=><details key={key}><summary>{labels[key]||key}</summary><HumanValue value={value} labels={labels}/></details>)}{detail.attachments?.length>0&&<section><h4>Documentos</h4>{detail.attachments.map((a:any)=><div key={a.id}><span>{a.original_name} · {a.scan_status}</span>{a.scan_status==='clean'&&detail.client_id&&<button className="btn" onClick={()=>run(async()=>{const {data,error}=await supabase.functions.invoke('portal-document-admin',{body:{action:'signed_url',documentId:a.id}});if(error||!data?.data?.url)throw new Error('No se pudo abrir el documento.');window.open(data.data.url,'_blank','noopener,noreferrer');})}>Abrir documento</button>}{a.scan_status==='error'&&<button className="btn" disabled={busy} onClick={()=>run(async()=>{await call('retry_document',{id:a.id});setDetail(await call('detail',{id:detail.id}));})}>Reintentar análisis</button>}</div>)}</section>}
 {!detail.client_id&&<section className="intake-link"><h4>Vincular identidad</h4><label>Paciente verificado<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Seleccionar ficha</option>{patients.filter(p=>p.clientUuid).map(p=><option key={p.clientUuid} value={p.clientUuid}>{p.name}</option>)}<option value="new">Crear ficha nueva después de verificar</option></select></label><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> Verifiqué la identidad y que corresponde a esta ficha.</label><button className="btn btn--primary" disabled={busy||!verified||!target} onClick={()=>run(async()=>{await call('link',{id:detail.id,clientId:target==='new'?null:target,createPatient:target==='new',identityVerified:true});setDetail(await call('detail',{id:detail.id}));})}>Vincular cuestionario</button></section>}
 {detail.state==='pending_review'&&<section><label>Nota de revisión<textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)}/></label><button className="btn btn--primary" disabled={busy} onClick={()=>run(async()=>{await call('review',{id:detail.id,note});setDetail(await call('detail',{id:detail.id}));})}>Marcar revisión clínica completa</button></section>}{detail.state==='reviewed'&&<button className="btn btn--primary" disabled={busy} onClick={()=>run(async()=>{await call('publish',{id:detail.id});setDetail(await call('detail',{id:detail.id}));})}>Publicar mediciones en el portal</button>}
 </article>}{clientId&&<Progress points={points}/>}</section>;
}
